// <auto-generated />
using System;
using Gestion_Hotel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_Hotel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240103135611_prix")]
    partial class prix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion_Hotel.Models.Chambre", b =>
                {
                    b.Property<int>("NumeroChambre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroChambre"));

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEtage")
                        .HasColumnType("int");

                    b.Property<string>("NumeroTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeChambre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("prix_chambre")
                        .HasColumnType("real");

                    b.HasKey("NumeroChambre");

                    b.ToTable("Chambres");
                });

            modelBuilder.Entity("Gestion_Hotel.Models.Reservation", b =>
                {
                    b.Property<int>("NumeroReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroReservation"));

                    b.Property<int?>("ChambreNumeroChambre")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumeroChambre")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroSalle")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroUser")
                        .HasColumnType("int");

                    b.Property<int?>("SalleReunionNumeroSalle")
                        .HasColumnType("int");

                    b.Property<int?>("UtilisateurNumeroUser")
                        .HasColumnType("int");

                    b.HasKey("NumeroReservation");

                    b.HasIndex("ChambreNumeroChambre");

                    b.HasIndex("SalleReunionNumeroSalle");

                    b.HasIndex("UtilisateurNumeroUser");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Gestion_Hotel.Models.SalleReunion", b =>
                {
                    b.Property<int>("NumeroSalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroSalle"));

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<int>("NumeroEtage")
                        .HasColumnType("int");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("prix_SR")
                        .HasColumnType("real");

                    b.HasKey("NumeroSalle");

                    b.ToTable("SallesReunion");
                });

            modelBuilder.Entity("Gestion_Hotel.Models.Utilisateur", b =>
                {
                    b.Property<int>("NumeroUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroUser"));

                    b.Property<string>("AdresseUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenomUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumeroUser");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Gestion_Hotel.Models.Reservation", b =>
                {
                    b.HasOne("Gestion_Hotel.Models.Chambre", "Chambre")
                        .WithMany("Reservations")
                        .HasForeignKey("ChambreNumeroChambre");

                    b.HasOne("Gestion_Hotel.Models.SalleReunion", "SalleReunion")
                        .WithMany("Reservations")
                        .HasForeignKey("SalleReunionNumeroSalle");

                    b.HasOne("Gestion_Hotel.Models.Utilisateur", "Utilisateur")
                        .WithMany("Reservations")
                        .HasForeignKey("UtilisateurNumeroUser");

                    b.Navigation("Chambre");

                    b.Navigation("SalleReunion");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Gestion_Hotel.Models.Chambre", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Gestion_Hotel.Models.SalleReunion", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Gestion_Hotel.Models.Utilisateur", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
